export const surahNames = [
  {
    number: 1,
    en: "Al-Fatiha",
    ar: "الفاتحة",
    arTashkeel: "الْفَاتِحَةُ",
    ayahs: 7,
    startPage: 1,
    endPage: 1,
  },
  {
    number: 2,
    en: "Al-Baqarah",
    ar: "البقرة",
    arTashkeel: "الْبَقَرَةُ",
    ayahs: 286,
    startPage: 2,
    endPage: 49,
  },
  {
    number: 3,
    en: "Aal-E-Imran",
    ar: "آل عمران",
    arTashkeel: "آلِ عِمْرَانَ",
    ayahs: 200,
    startPage: 50,
    endPage: 76,
  },
  {
    number: 4,
    en: "An-Nisa",
    ar: "النساء",
    arTashkeel: "النِّسَاءُ",
    ayahs: 176,
    startPage: 77,
    endPage: 106,
  },
  {
    number: 5,
    en: "Al-Maidah",
    ar: "المائدة",
    arTashkeel: "الْمَائِدَةُ",
    ayahs: 120,
    startPage: 106,
    endPage: 127,
  },
  {
    number: 6,
    en: "Al-Anam",
    ar: "الأنعام",
    arTashkeel: "الْأَنْعَامُ",
    ayahs: 165,
    startPage: 128,
    endPage: 150,
  },
  {
    number: 7,
    en: "Al-Araf",
    ar: "الأعراف",
    arTashkeel: "الْأَعْرَافُ",
    ayahs: 206,
    startPage: 151,
    endPage: 176,
  },
  {
    number: 8,
    en: "Al-Anfal",
    ar: "الأنفال",
    arTashkeel: "الْأَنْفَالُ",
    ayahs: 75,
    startPage: 177,
    endPage: 186,
  },
  {
    number: 9,
    en: "At-Tawbah",
    ar: "التوبة",
    arTashkeel: "التَّوْبَةُ",
    ayahs: 129,
    startPage: 187,
    endPage: 207,
  },
  {
    number: 10,
    en: "Yunus",
    ar: "يونس",
    arTashkeel: "يُونُسُ",
    ayahs: 109,
    startPage: 208,
    endPage: 221,
  },
  {
    number: 11,
    en: "Hud",
    ar: "هود",
    arTashkeel: "هُودٌ",
    ayahs: 123,
    startPage: 221,
    endPage: 235,
  },
  {
    number: 12,
    en: "Yusuf",
    ar: "يوسف",
    arTashkeel: "يُوسُفُ",
    ayahs: 111,
    startPage: 235,
    endPage: 248,
  },
  {
    number: 13,
    en: "Ar-Rad",
    ar: "الرعد",
    arTashkeel: "الرَّعْدُ",
    ayahs: 43,
    startPage: 249,
    endPage: 255,
  },
  {
    number: 14,
    en: "Ibrahim",
    ar: "إبراهيم",
    arTashkeel: "إِبْرَاهِيمُ",
    ayahs: 52,
    startPage: 255,
    endPage: 261,
  },
  {
    number: 15,
    en: "Al-Hijr",
    ar: "الحجر",
    arTashkeel: "الْحِجْرُ",
    ayahs: 99,
    startPage: 262,
    endPage: 267,
  },
  {
    number: 16,
    en: "An-Nahl",
    ar: "النحل",
    arTashkeel: "النَّحْلُ",
    ayahs: 128,
    startPage: 267,
    endPage: 281,
  },
  {
    number: 17,
    en: "Al-Isra",
    ar: "الإسراء",
    arTashkeel: "الْإِسْرَاءُ",
    ayahs: 111,
    startPage: 282,
    endPage: 293,
  },
  {
    number: 18,
    en: "Al-Kahf",
    ar: "الكهف",
    arTashkeel: "الْكَهْفُ",
    ayahs: 110,
    startPage: 293,
    endPage: 304,
  },
  {
    number: 19,
    en: "Maryam",
    ar: "مريم",
    arTashkeel: "مَرْيَمُ",
    ayahs: 98,
    startPage: 305,
    endPage: 312,
  },
  {
    number: 20,
    en: "Taha",
    ar: "طه",
    arTashkeel: "طَهَ",
    ayahs: 135,
    startPage: 312,
    endPage: 321,
  },
  {
    number: 21,
    en: "Al-Anbiya",
    ar: "الأنبياء",
    arTashkeel: "الْأَنْبِيَاءُ",
    ayahs: 112,
    startPage: 322,
    endPage: 331,
  },
  {
    number: 22,
    en: "Al-Hajj",
    ar: "الحج",
    arTashkeel: "الْحَجُّ",
    ayahs: 78,
    startPage: 332,
    endPage: 341,
  },
  {
    number: 23,
    en: "Al-Muminun",
    ar: "المؤمنون",
    arTashkeel: "الْمُؤْمِنُونَ",
    ayahs: 118,
    startPage: 342,
    endPage: 349,
  },
  {
    number: 24,
    en: "An-Nur",
    ar: "النور",
    arTashkeel: "النُّورُ",
    ayahs: 64,
    startPage: 350,
    endPage: 359,
  },
  {
    number: 25,
    en: "Al-Furqan",
    ar: "الفرقان",
    arTashkeel: "الْفُرْقَانُ",
    ayahs: 77,
    startPage: 359,
    endPage: 366,
  },
  {
    number: 26,
    en: "Ash-Shuara",
    ar: "الشعراء",
    arTashkeel: "الشُّعَرَاءُ",
    ayahs: 227,
    startPage: 367,
    endPage: 376,
  },
  {
    number: 27,
    en: "An-Naml",
    ar: "النمل",
    arTashkeel: "النَّمْلُ",
    ayahs: 93,
    startPage: 377,
    endPage: 385,
  },
  {
    number: 28,
    en: "Al-Qasas",
    ar: "القصص",
    arTashkeel: "الْقَصَصُ",
    ayahs: 88,
    startPage: 385,
    endPage: 396,
  },
  {
    number: 29,
    en: "Al-Ankabut",
    ar: "العنكبوت",
    arTashkeel: "الْعَنْكَبُوتُ",
    ayahs: 69,
    startPage: 396,
    endPage: 404,
  },
  {
    number: 30,
    en: "Ar-Rum",
    ar: "الروم",
    arTashkeel: "الرُّومُ",
    ayahs: 60,
    startPage: 404,
    endPage: 410,
  },
  {
    number: 31,
    en: "Luqman",
    ar: "لقمان",
    arTashkeel: "لُقْمَانُ",
    ayahs: 34,
    startPage: 411,
    endPage: 414,
  },
  {
    number: 32,
    en: "As-Sajda",
    ar: "السجدة",
    arTashkeel: "السَّجْدَةُ",
    ayahs: 30,
    startPage: 415,
    endPage: 417,
  },
  {
    number: 33,
    en: "Al-Ahzab",
    ar: "الأحزاب",
    arTashkeel: "الْأَحْزَابُ",
    ayahs: 73,
    startPage: 418,
    endPage: 427,
  },
  {
    number: 34,
    en: "Saba",
    ar: "سبأ",
    arTashkeel: "سَبَأٌ",
    ayahs: 54,
    startPage: 428,
    endPage: 434,
  },
  {
    number: 35,
    en: "Fatir",
    ar: "فاطر",
    arTashkeel: "فَاطِرٌ",
    ayahs: 45,
    startPage: 434,
    endPage: 440,
  },
  {
    number: 36,
    en: "Yaseen",
    ar: "يس",
    arTashkeel: "يَسَ",
    ayahs: 83,
    startPage: 440,
    endPage: 445,
  },
  {
    number: 37,
    en: "As-Saffat",
    ar: "الصافات",
    arTashkeel: "الصَّافَّاتُ",
    ayahs: 182,
    startPage: 446,
    endPage: 452,
  },
  {
    number: 38,
    en: "Sad",
    ar: "ص",
    arTashkeel: "صَ",
    ayahs: 88,
    startPage: 453,
    endPage: 458,
  },
  {
    number: 39,
    en: "Az-Zumar",
    ar: "الزمر",
    arTashkeel: "الزُّمَرُ",
    ayahs: 75,
    startPage: 458,
    endPage: 467,
  },
  {
    number: 40,
    en: "Ghafir",
    ar: "غافر",
    arTashkeel: "غَافِرٌ",
    ayahs: 85,
    startPage: 467,
    endPage: 476,
  },
  {
    number: 41,
    en: "Fussilat",
    ar: "فصلت",
    arTashkeel: "فُصِّلَتْ",
    ayahs: 54,
    startPage: 477,
    endPage: 482,
  },
  {
    number: 42,
    en: "Ash-Shura",
    ar: "الشورى",
    arTashkeel: "الشُّورَى",
    ayahs: 53,
    startPage: 483,
    endPage: 489,
  },
  {
    number: 43,
    en: "Az-Zukhruf",
    ar: "الزخرف",
    arTashkeel: "الزُّخْرُفُ",
    ayahs: 89,
    startPage: 489,
    endPage: 495,
  },
  {
    number: 44,
    en: "Ad-Dukhan",
    ar: "الدخان",
    arTashkeel: "الدُّخَانُ",
    ayahs: 59,
    startPage: 496,
    endPage: 498,
  },
  {
    number: 45,
    en: "Al-Jathiya",
    ar: "الجاثية",
    arTashkeel: "الْجَاثِيَةُ",
    ayahs: 37,
    startPage: 499,
    endPage: 502,
  },
  {
    number: 46,
    en: "Al-Ahqaf",
    ar: "الأحقاف",
    arTashkeel: "الْأَحْقَافُ",
    ayahs: 35,
    startPage: 502,
    endPage: 506,
  },
  {
    number: 47,
    en: "Muhammad",
    ar: "محمد",
    arTashkeel: "مُحَمَّدٌ",
    ayahs: 38,
    startPage: 507,
    endPage: 510,
  },
  {
    number: 48,
    en: "Al-Fath",
    ar: "الفتح",
    arTashkeel: "الْفَتْحُ",
    ayahs: 29,
    startPage: 511,
    endPage: 515,
  },
  {
    number: 49,
    en: "Al-Hujraat",
    ar: "الحجرات",
    arTashkeel: "الْحُجُرَاتُ",
    ayahs: 18,
    startPage: 515,
    endPage: 517,
  },
  {
    number: 50,
    en: "Qaf",
    ar: "ق",
    arTashkeel: "قَ",
    ayahs: 45,
    startPage: 518,
    endPage: 520,
  },
  {
    number: 51,
    en: "Adh-Dhariyat",
    ar: "الذاريات",
    arTashkeel: "الذَّارِيَاتُ",
    ayahs: 60,
    startPage: 520,
    endPage: 523,
  },
  {
    number: 52,
    en: "At-Tur",
    ar: "الطور",
    arTashkeel: "الطُّورُ",
    ayahs: 49,
    startPage: 523,
    endPage: 525,
  },
  {
    number: 53,
    en: "An-Najm",
    ar: "النجم",
    arTashkeel: "النَّجْمُ",
    ayahs: 62,
    startPage: 526,
    endPage: 528,
  },
  {
    number: 54,
    en: "Al-Qamar",
    ar: "القمر",
    arTashkeel: "الْقَمَرُ",
    ayahs: 55,
    startPage: 528,
    endPage: 531,
  },
  {
    number: 55,
    en: "Ar-Rahman",
    ar: "الرحمن",
    arTashkeel: "الرَّحْمَٰنُ",
    ayahs: 78,
    startPage: 531,
    endPage: 534,
  },
  {
    number: 56,
    en: "Al-Waqia",
    ar: "الواقعة",
    arTashkeel: "الْوَاقِعَةُ",
    ayahs: 96,
    startPage: 534,
    endPage: 537,
  },
  {
    number: 57,
    en: "Al-Hadid",
    ar: "الحديد",
    arTashkeel: "الْحَدِيدُ",
    ayahs: 29,
    startPage: 537,
    endPage: 541,
  },
  {
    number: 58,
    en: "Al-Mujadila",
    ar: "المجادلة",
    arTashkeel: "الْمُجَادَلَةُ",
    ayahs: 22,
    startPage: 542,
    endPage: 545,
  },
  {
    number: 59,
    en: "Al-Hashr",
    ar: "الحشر",
    arTashkeel: "الْحَشْرُ",
    ayahs: 24,
    startPage: 545,
    endPage: 548,
  },
  {
    number: 60,
    en: "Al-Mumtahina",
    ar: "الممتحنة",
    arTashkeel: "الْمُمْتَحَنَةُ",
    ayahs: 13,
    startPage: 549,
    endPage: 551,
  },
  {
    number: 61,
    en: "As-Saff",
    ar: "الصف",
    arTashkeel: "الصَّفُّ",
    ayahs: 14,
    startPage: 551,
    endPage: 552,
  },
  {
    number: 62,
    en: "Al-Jumua",
    ar: "الجمعة",
    arTashkeel: "الْجُمُعَةُ",
    ayahs: 11,
    startPage: 553,
    endPage: 554,
  },
  {
    number: 63,
    en: "Al-Munafiqun",
    ar: "المنافقون",
    arTashkeel: "الْمُنَافِقُونَ",
    ayahs: 11,
    startPage: 554,
    endPage: 555,
  },
  {
    number: 64,
    en: "At-Taghabun",
    ar: "التغابن",
    arTashkeel: "التَّغَابُنُ",
    ayahs: 18,
    startPage: 556,
    endPage: 557,
  },
  {
    number: 65,
    en: "At-Talaq",
    ar: "الطلاق",
    arTashkeel: "الطَّلَاقُ",
    ayahs: 12,
    startPage: 558,
    endPage: 559,
  },
  {
    number: 66,
    en: "At-Tahrim",
    ar: "التحريم",
    arTashkeel: "التَّحْرِيمُ",
    ayahs: 12,
    startPage: 560,
    endPage: 561,
  },
  {
    number: 67,
    en: "Al-Mulk",
    ar: "الملك",
    arTashkeel: "الْمُلْكُ",
    ayahs: 30,
    startPage: 562,
    endPage: 564,
  },
  {
    number: 68,
    en: "Al-Qalam",
    ar: "القلم",
    arTashkeel: "الْقَلَمُ",
    ayahs: 52,
    startPage: 564,
    endPage: 566,
  },
  {
    number: 69,
    en: "Al-Haaqqa",
    ar: "الحاقة",
    arTashkeel: "الْحَاقَّةُ",
    ayahs: 52,
    startPage: 566,
    endPage: 568,
  },
  {
    number: 70,
    en: "Al-Maarij",
    ar: "المعارج",
    arTashkeel: "الْمَعَارِجُ",
    ayahs: 44,
    startPage: 568,
    endPage: 570,
  },
  {
    number: 71,
    en: "Nuh",
    ar: "نوح",
    arTashkeel: "نُوحٌ",
    ayahs: 28,
    startPage: 570,
    endPage: 571,
  },
  {
    number: 72,
    en: "Al-Jinn",
    ar: "الجن",
    arTashkeel: "الْجِنُّ",
    ayahs: 28,
    startPage: 572,
    endPage: 573,
  },
  {
    number: 73,
    en: "Al-Muzzammil",
    ar: "المزمل",
    arTashkeel: "الْمُزَّمِّلُ",
    ayahs: 20,
    startPage: 574,
    endPage: 575,
  },
  {
    number: 74,
    en: "Al-Muddathir",
    ar: "المدثر",
    arTashkeel: "الْمُدَّثِّرُ",
    ayahs: 56,
    startPage: 575,
    endPage: 577,
  },
  {
    number: 75,
    en: "Al-Qiyama",
    ar: "القيامة",
    arTashkeel: "الْقِيَامَةُ",
    ayahs: 40,
    startPage: 577,
    endPage: 578,
  },
  {
    number: 76,
    en: "Al-Insan",
    ar: "الإنسان",
    arTashkeel: "الْإِنْسَانُ",
    ayahs: 31,
    startPage: 578,
    endPage: 580,
  },
  {
    number: 77,
    en: "Al-Mursalat",
    ar: "المرسلات",
    arTashkeel: "الْمُرْسَلَاتُ",
    ayahs: 50,
    startPage: 580,
    endPage: 581,
  },
  {
    number: 78,
    en: "An-Naba",
    ar: "النبأ",
    arTashkeel: "النَّبَأُ",
    ayahs: 40,
    startPage: 582,
    endPage: 583,
  },
  {
    number: 79,
    en: "An-Naziat",
    ar: "النازعات",
    arTashkeel: "النَّازِعَاتُ",
    ayahs: 46,
    startPage: 583,
    endPage: 584,
  },
  {
    number: 80,
    en: "Abasa",
    ar: "عبس",
    arTashkeel: "عَبَسَ",
    ayahs: 42,
    startPage: 585,
    endPage: 585,
  },
  {
    number: 81,
    en: "At-Takwir",
    ar: "التكوير",
    arTashkeel: "التَّكْوِيرُ",
    ayahs: 29,
    startPage: 586,
    endPage: 586,
  },
  {
    number: 82,
    en: "Al-Infitar",
    ar: "الإنفطار",
    arTashkeel: "الْإِنْفِطَارُ",
    ayahs: 19,
    startPage: 587,
    endPage: 587,
  },
  {
    number: 83,
    en: "Al-Mutaffifin",
    ar: "المطففين",
    arTashkeel: "الْمُطَفِّفِينَ",
    ayahs: 36,
    startPage: 587,
    endPage: 589,
  },
  {
    number: 84,
    en: "Al-Inshiqaq",
    ar: "الإنشقاق",
    arTashkeel: "الْإِنْشِقَاقُ",
    ayahs: 25,
    startPage: 589,
    endPage: 589,
  },
  {
    number: 85,
    en: "Al-Buruj",
    ar: "البروج",
    arTashkeel: "الْبُرُوجُ",
    ayahs: 22,
    startPage: 590,
    endPage: 590,
  },
  {
    number: 86,
    en: "At-Tariq",
    ar: "الطارق",
    arTashkeel: "الطَّارِقُ",
    ayahs: 17,
    startPage: 591,
    endPage: 591,
  },
  {
    number: 87,
    en: "Al-Ala",
    ar: "الأعلى",
    arTashkeel: "الْأَعْلَى",
    ayahs: 19,
    startPage: 591,
    endPage: 592,
  },
  {
    number: 88,
    en: "Al-Ghashiya",
    ar: "الغاشية",
    arTashkeel: "الْغَاشِيَةُ",
    ayahs: 26,
    startPage: 592,
    endPage: 592,
  },
  {
    number: 89,
    en: "Al-Fajr",
    ar: "الفجر",
    arTashkeel: "الْفَجْرُ",
    ayahs: 30,
    startPage: 593,
    endPage: 594,
  },
  {
    number: 90,
    en: "Al-Balad",
    ar: "البلد",
    arTashkeel: "الْبَلَدُ",
    ayahs: 20,
    startPage: 594,
    endPage: 594,
  },
  {
    number: 91,
    en: "Ash-Shams",
    ar: "الشمس",
    arTashkeel: "الشَّمْسُ",
    ayahs: 15,
    startPage: 595,
    endPage: 595,
  },
  {
    number: 92,
    en: "Al-Lail",
    ar: "الليل",
    arTashkeel: "اللَّيْلُ",
    ayahs: 21,
    startPage: 595,
    endPage: 596,
  },
  {
    number: 93,
    en: "Ad-Duha",
    ar: "الضحى",
    arTashkeel: "الضُّحَى",
    ayahs: 11,
    startPage: 596,
    endPage: 596,
  },
  {
    number: 94,
    en: "Ash-Sharh",
    ar: "الشرح",
    arTashkeel: "الشَّرْحُ",
    ayahs: 8,
    startPage: 596,
    endPage: 596,
  },
  {
    number: 95,
    en: "At-Tin",
    ar: "التين",
    arTashkeel: "التِّينُ",
    ayahs: 8,
    startPage: 597,
    endPage: 597,
  },
  {
    number: 96,
    en: "Al-Alaq",
    ar: "العلق",
    arTashkeel: "الْعَلَقُ",
    ayahs: 19,
    startPage: 597,
    endPage: 597,
  },
  {
    number: 97,
    en: "Al-Qadr",
    ar: "القدر",
    arTashkeel: "الْقَدْرُ",
    ayahs: 5,
    startPage: 598,
    endPage: 598,
  },
  {
    number: 98,
    en: "Al-Bayyina",
    ar: "البينة",
    arTashkeel: "الْبَيِّنَةُ",
    ayahs: 8,
    startPage: 598,
    endPage: 599,
  },
  {
    number: 99,
    en: "Az-Zalzala",
    ar: "الزلزلة",
    arTashkeel: "الزَّلْزَلَةُ",
    ayahs: 8,
    startPage: 599,
    endPage: 599,
  },
  {
    number: 100,
    en: "Al-Adiyat",
    ar: "العاديات",
    arTashkeel: "الْعَادِيَاتُ",
    ayahs: 11,
    startPage: 599,
    endPage: 600,
  },
  {
    number: 101,
    en: "Al-Qaria",
    ar: "القارعة",
    arTashkeel: "الْقَارِعَةُ",
    ayahs: 11,
    startPage: 600,
    endPage: 600,
  },
  {
    number: 102,
    en: "At-Takathur",
    ar: "التكاثر",
    arTashkeel: "التَّكَاثُرُ",
    ayahs: 8,
    startPage: 600,
    endPage: 600,
  },
  {
    number: 103,
    en: "Al-Asr",
    ar: "العصر",
    arTashkeel: "الْعَصْرُ",
    ayahs: 3,
    startPage: 601,
    endPage: 601,
  },
  {
    number: 104,
    en: "Al-Humaza",
    ar: "الهمزة",
    arTashkeel: "الْهُمَزَةُ",
    ayahs: 9,
    startPage: 601,
    endPage: 601,
  },
  {
    number: 105,
    en: "Al-Fil",
    ar: "الفيل",
    arTashkeel: "الْفِيلُ",
    ayahs: 5,
    startPage: 601,
    endPage: 601,
  },
  {
    number: 106,
    en: "Quraish",
    ar: "قريش",
    arTashkeel: "قُرَيْشٌ",
    ayahs: 4,
    startPage: 602,
    endPage: 602,
  },
  {
    number: 107,
    en: "Al-Maun",
    ar: "الماعون",
    arTashkeel: "الْمَاعُونُ",
    ayahs: 7,
    startPage: 602,
    endPage: 602,
  },
  {
    number: 108,
    en: "Al-Kawthar",
    ar: "الكوثر",
    arTashkeel: "الْكَوْثَرُ",
    ayahs: 3,
    startPage: 602,
    endPage: 602,
  },
  {
    number: 109,
    en: "Al-Kafiroon",
    ar: "الكافرون",
    arTashkeel: "الْكَافِرُونَ",
    ayahs: 6,
    startPage: 603,
    endPage: 603,
  },
  {
    number: 110,
    en: "An-Nasr",
    ar: "النصر",
    arTashkeel: "النَّصْرُ",
    ayahs: 3,
    startPage: 603,
    endPage: 603,
  },
  {
    number: 111,
    en: "Al-Masad",
    ar: "المسد",
    arTashkeel: "الْمَسَدُ",
    ayahs: 5,
    startPage: 603,
    endPage: 603,
  },
  {
    number: 112,
    en: "Al-Ikhlas",
    ar: "الإخلاص",
    arTashkeel: "الْإِخْلَاصُ",
    ayahs: 4,
    startPage: 604,
    endPage: 604,
  },
  {
    number: 113,
    en: "Al-Falaq",
    ar: "الفلق",
    arTashkeel: "الْفَلَقُ",
    ayahs: 5,
    startPage: 604,
    endPage: 604,
  },
  {
    number: 114,
    en: "An-Nas",
    ar: "الناس",
    arTashkeel: "النَّاسُ",
    ayahs: 6,
    startPage: 604,
    endPage: 604,
  },
];

export const juzNames = [
  { number: 1, name: { en: "Juz' 1", ar: "الجزء 1" }, surahs: 2, startPage: 1 },
  {
    number: 2,
    name: { en: "Juz' 2", ar: "الجزء 2" },
    surahs: 1,
    startPage: 22,
  },
  {
    number: 3,
    name: { en: "Juz' 3", ar: "الجزء 3" },
    surahs: 2,
    startPage: 42,
  },
  {
    number: 4,
    name: { en: "Juz' 4", ar: "الجزء 4" },
    surahs: 2,
    startPage: 62,
  },
  {
    number: 5,
    name: { en: "Juz' 5", ar: "الجزء 5" },
    surahs: 2,
    startPage: 82,
  },
  {
    number: 6,
    name: { en: "Juz' 6", ar: "الجزء 6" },
    surahs: 2,
    startPage: 102,
  },
  {
    number: 7,
    name: { en: "Juz' 7", ar: "الجزء 7" },
    surahs: 2,
    startPage: 122,
  },
  {
    number: 8,
    name: { en: "Juz' 8", ar: "الجزء 8" },
    surahs: 2,
    startPage: 142,
  },
  {
    number: 9,
    name: { en: "Juz' 9", ar: "الجزء 9" },
    surahs: 2,
    startPage: 162,
  },
  {
    number: 10,
    name: { en: "Juz' 10", ar: "الجزء 10" },
    surahs: 2,
    startPage: 182,
  },
  {
    number: 11,
    name: { en: "Juz' 11", ar: "الجزء 11" },
    surahs: 2,
    startPage: 202,
  },
  {
    number: 12,
    name: { en: "Juz' 12", ar: "الجزء 12" },
    surahs: 2,
    startPage: 222,
  },
  {
    number: 13,
    name: { en: "Juz' 13", ar: "الجزء 13" },
    surahs: 2,
    startPage: 242,
  },
  {
    number: 14,
    name: { en: "Juz' 14", ar: "الجزء 14" },
    surahs: 2,
    startPage: 262,
  },
  {
    number: 15,
    name: { en: "Juz' 15", ar: "الجزء 15" },
    surahs: 2,
    startPage: 282,
  },
  {
    number: 16,
    name: { en: "Juz' 16", ar: "الجزء 16" },
    surahs: 2,
    startPage: 302,
  },
  {
    number: 17,
    name: { en: "Juz' 17", ar: "الجزء 17" },
    surahs: 2,
    startPage: 322,
  },
  {
    number: 18,
    name: { en: "Juz' 18", ar: "الجزء 18" },
    surahs: 2,
    startPage: 342,
  },
  {
    number: 19,
    name: { en: "Juz' 19", ar: "الجزء 19" },
    surahs: 2,
    startPage: 362,
  },
  {
    number: 20,
    name: { en: "Juz' 20", ar: "الجزء 20" },
    surahs: 2,
    startPage: 382,
  },
  {
    number: 21,
    name: { en: "Juz' 21", ar: "الجزء 21" },
    surahs: 3,
    startPage: 402,
  },
  {
    number: 22,
    name: { en: "Juz' 22", ar: "الجزء 22" },
    surahs: 3,
    startPage: 422,
  },
  {
    number: 23,
    name: { en: "Juz' 23", ar: "الجزء 23" },
    surahs: 3,
    startPage: 442,
  },
  {
    number: 24,
    name: { en: "Juz' 24", ar: "الجزء 24" },
    surahs: 3,
    startPage: 462,
  },
  {
    number: 25,
    name: { en: "Juz' 25", ar: "الجزء 25" },
    surahs: 3,
    startPage: 482,
  },
  {
    number: 26,
    name: { en: "Juz' 26", ar: "الجزء 26" },
    surahs: 3,
    startPage: 502,
  },
  {
    number: 27,
    name: { en: "Juz' 27", ar: "الجزء 27" },
    surahs: 3,
    startPage: 522,
  },
  {
    number: 28,
    name: { en: "Juz' 28", ar: "الجزء 28" },
    surahs: 3,
    startPage: 542,
  },
  {
    number: 29,
    name: { en: "Juz' 29", ar: "الجزء 29" },
    surahs: 11,
    startPage: 562,
  },
  {
    number: 30,
    name: { en: "Juz' 30", ar: "الجزء 30" },
    surahs: 37,
    startPage: 582,
  },
];
