import { IconDefinition } from "@fortawesome/fontawesome-svg-core";
import {
  faRadio,
  faMicrophone,
  faGlobe,
  faScaleBalanced,
  faHamsa,
} from "@fortawesome/free-solid-svg-icons";

export type RadioCategory = "main" | "thematic" | "reciters" | "translations";

export interface RadioStation {
  nameAr: string;
  nameEn: string;
  url: string;
  category: RadioCategory;
  icon: IconDefinition;
}

export const radioCategories: RadioCategory[] = [
  "main",
  "thematic",
  "reciters",
  "translations",
];

export const radioStations: RadioStation[] = [
  // ── Main ─────────────────────────────────
  // {
  //   nameAr: "إذاعة القرآن الكريم — القاهرة",
  //   nameEn: "Holy Quran Radio — Cairo",
  //   url: "https://n03.radiojar.com/8s5u5tpdtwzuv",
  //   category: "main",
  //   icon: faRadio,
  // },

  // ── Thematic ─────────────────────────────
  {
    nameAr: "الإذاعة العامة",
    nameEn: "Main Quran Radio",
    url: "http://live.mp3quran.net:9998",
    category: "thematic",
    icon: faRadio,
  },
  {
    nameAr: "تلاوات خاشعة - 1",
    nameEn: "Beautiful Recitations - 1",
    url: "https://qurango.net/radio/tarateel",
    category: "thematic",
    icon: faMicrophone,
  },

  {
    nameAr: "تلاوات خاشعة - 2",
    nameEn: "Beautiful Recitations - 2",
    url: "http://live.mp3quran.net:9992",
    category: "thematic",
    icon: faMicrophone,
  },
  {
    nameAr: "الرقية الشرعية",
    nameEn: "Ruqyah Radio",
    url: "http://live.mp3quran.net:9936",
    category: "thematic",
    icon: faHamsa,
  },
  {
    nameAr: "الفتاوى الشرعية",
    nameEn: "Fatawa Radio",
    url: "http://live.mp3quran.net:8014",
    category: "thematic",
    icon: faScaleBalanced,
  },

  // ── Reciters ─────────────────────────────
  {
    nameAr: "إبراهيم الأخضر",
    nameEn: "Ibrahim Al-Akhdar",
    url: "http://live.mp3quran.net:9946",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "أبو بكر الشاطري",
    nameEn: "Abu Bakr Al-Shatri",
    url: "http://live.mp3quran.net:9966",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "أحمد بن علي العجمي",
    nameEn: "Ahmad Al-Ajamy",
    url: "http://live.mp3quran.net:8008",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "أحمد الحواشي",
    nameEn: "Ahmad Al-Hawashi",
    url: "http://live.mp3quran.net:9928",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "أحمد صابر",
    nameEn: "Ahmad Saber",
    url: "http://live.mp3quran.net:9922",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "أحمد نعينع",
    nameEn: "Ahmad Nauina",
    url: "http://live.mp3quran.net:9904",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "أكرم العلاقمي",
    nameEn: "Akram Al-Alaqmi",
    url: "http://live.mp3quran.net:9918",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "إدريس أبكر",
    nameEn: "Idrees Abkar",
    url: "http://live.mp3quran.net:9968",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "الزين محمد أحمد",
    nameEn: "Al-Zain Mohammad Ahmad",
    url: "http://live.mp3quran.net:9914",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "القارئ ياسين",
    nameEn: "Al-Qari Yaseen",
    url: "http://live.mp3quran.net:9908",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "العيون الكوشي",
    nameEn: "Al-Oyoon Al-Kushi",
    url: "http://live.mp3quran.net:9912",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "توفيق الصايغ",
    nameEn: "Tawfeeq As-Sayegh",
    url: "http://live.mp3quran.net:9906",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "جمال شاكر عبدالله",
    nameEn: "Jamal Shaker Abdullah",
    url: "http://live.mp3quran.net:9900",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "جمعان العصيمي",
    nameEn: "Jamaan Al-Osaimi",
    url: "http://live.mp3quran.net:9950",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "حاتم فريد الواعر",
    nameEn: "Hatem Fareed Al-Waer",
    url: "http://live.mp3quran.net:9898",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "خالد القحطاني",
    nameEn: "Khaled Al-Qahtani",
    url: "http://live.mp3quran.net:9970",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "خالد عبدالكافي",
    nameEn: "Khalid Abdul-Kafi",
    url: "http://live.mp3quran.net:9894",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "خالد المهنا",
    nameEn: "Khalid Al-Mohana",
    url: "http://live.mp3quran.net:9896",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "خليفة الطنيجي",
    nameEn: "Khalifa Al-Tunaiji",
    url: "http://live.mp3quran.net:9892",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "سعد الغامدي",
    nameEn: "Saad Al-Ghamdi",
    url: "http://live.mp3quran.net:8004",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "سعود الشريم",
    nameEn: "Saud Al-Shuraim",
    url: "http://live.mp3quran.net:9986",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "سهل ياسين",
    nameEn: "Sahl Yaseen",
    url: "http://live.mp3quran.net:9888",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "زكي داغستاني",
    nameEn: "Zaki Daghistani",
    url: "http://live.mp3quran.net:9890",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "سيد رمضان",
    nameEn: "Sayyid Ramadan",
    url: "http://live.mp3quran.net:9886",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "شيرزاد عبدالرحمن طاهر",
    nameEn: "Shirazad Taher",
    url: "http://live.mp3quran.net:9884",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "صابر عبدالحكم",
    nameEn: "Saber Abdul-Hakam",
    url: "http://live.mp3quran.net:9952",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "صلاح البدير",
    nameEn: "Salah Al-Budair",
    url: "http://live.mp3quran.net:9882",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "صلاح الهاشم",
    nameEn: "Salah Al-Hashim",
    url: "http://live.mp3quran.net:9880",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "صلاح بوخاطر",
    nameEn: "Salah Bukhatir",
    url: "http://live.mp3quran.net:9878",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "طارق عبدالغني دعوب",
    nameEn: "Tariq Abdul-Ghani Daawob",
    url: "http://live.mp3quran.net:9876",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "عادل ريان",
    nameEn: "Adel Rayan",
    url: "http://live.mp3quran.net:9872",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "عادل الكلباني",
    nameEn: "Adel Al-Kalbani",
    url: "http://live.mp3quran.net:9874",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "عبدالبارئ الثبيتي",
    nameEn: "Abdul-Bari Al-Thubaiti",
    url: "http://live.mp3quran.net:9870",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "عبدالبارئ محمد",
    nameEn: "Abdul-Bari Mohammad",
    url: "http://live.mp3quran.net:9868",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "عبدالباسط عبدالصمد — مرتل",
    nameEn: "Abdul-Basit (Murattal)",
    url: "http://live.mp3quran.net:9974",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "عبدالباسط عبدالصمد — مجوّد",
    nameEn: "Abdul-Basit (Mujawwad)",
    url: "http://live.mp3quran.net:9956",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "عبدالباسط عبدالصمد — منوّع",
    nameEn: "Abdul-Basit (Mixed)",
    url: "http://live.mp3quran.net:9980",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "عبدالرحمن السديس",
    nameEn: "Abdul-Rahman Al-Sudais",
    url: "http://live.mp3quran.net:9988",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "عبدالرشيد صوفي — رواية ١",
    nameEn: "Abdul-Rashid Sufi (Riwayah 1)",
    url: "http://live.mp3quran.net:9866",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "عبدالرشيد صوفي — رواية ٢",
    nameEn: "Abdul-Rashid Sufi (Riwayah 2)",
    url: "http://live.mp3quran.net:9864",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "عبدالعزيز الأحمد",
    nameEn: "Abdul-Aziz Al-Ahmad",
    url: "http://live.mp3quran.net:9862",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "عبدالله المطرود",
    nameEn: "Abdullah Al-Matrod",
    url: "http://live.mp3quran.net:9858",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "عبدالله بصفر",
    nameEn: "Abdullah Basfar",
    url: "http://live.mp3quran.net:9954",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "عبدالله خياط",
    nameEn: "Abdullah Khayyat",
    url: "http://live.mp3quran.net:9948",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "عبدالله عواد الجهني",
    nameEn: "Abdullah Al-Juhany",
    url: "http://live.mp3quran.net:9944",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "عبدالله الكندري",
    nameEn: "Abdullah Al-Kandari",
    url: "http://live.mp3quran.net:9860",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "عبدالمحسن الحارثي",
    nameEn: "Abdul-Muhsin Al-Harthi",
    url: "http://live.mp3quran.net:9856",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "عبدالمحسن القاسم",
    nameEn: "Abdul-Muhsin Al-Qasim",
    url: "http://live.mp3quran.net:9852",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "عبدالمحسن العبيكان",
    nameEn: "Abdul-Muhsin Al-Obaikan",
    url: "http://live.mp3quran.net:9854",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "عبدالهادي أحمد كناكري",
    nameEn: "Abdul-Hadi Kanakeri",
    url: "http://live.mp3quran.net:9850",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "عبدالودود حنيف",
    nameEn: "Abdul-Wadood Haneef",
    url: "http://live.mp3quran.net:9848",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "علي الحذيفي — رواية ١",
    nameEn: "Ali Al-Hudhaifi (Riwayah 1)",
    url: "http://live.mp3quran.net:9844",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "علي الحذيفي — رواية ٢",
    nameEn: "Ali Al-Hudhaifi (Riwayah 2)",
    url: "http://live.mp3quran.net:9846",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "علي جابر",
    nameEn: "Ali Jaber",
    url: "http://live.mp3quran.net:9964",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "علي حجاج السويسي",
    nameEn: "Ali Hajjaj Al-Souasi",
    url: "http://live.mp3quran.net:9842",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "عماد زهير حافظ",
    nameEn: "Emad Zahir Hafez",
    url: "http://live.mp3quran.net:9840",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "عمر القزابري",
    nameEn: "Omar Al-Qazabri",
    url: "http://live.mp3quran.net:9838",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "فارس عباد",
    nameEn: "Fares Abbad",
    url: "http://live.mp3quran.net:9972",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "الفاتح محمد الزبير",
    nameEn: "Al-Fateh Al-Zubair",
    url: "http://live.mp3quran.net:9910",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "الدوكالي محمد العالم",
    nameEn: "Al-Dukali Mohammad Al-Aalim",
    url: "http://live.mp3quran.net:9916",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "ابراهيم الدوسري",
    nameEn: "Ibrahim Al-Dosari",
    url: "http://live.mp3quran.net:9902",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "ماهر المعيقلي",
    nameEn: "Maher Al-Muaiqly",
    url: "http://live.mp3quran.net:8002",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "ماهر شخاشيرو",
    nameEn: "Maher Shakhashiru",
    url: "http://live.mp3quran.net:9836",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "محمد الطبلاوي",
    nameEn: "Mohammad Al-Tablawi",
    url: "http://live.mp3quran.net:9834",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "محمد اللحيدان",
    nameEn: "Mohammed Al-Luhaidan",
    url: "http://live.mp3quran.net:9832",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "محمد أيوب",
    nameEn: "Mohammed Ayyub",
    url: "http://live.mp3quran.net:9960",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "محمد صالح عالم شاه",
    nameEn: "Mohammad Saleh Alim Shah",
    url: "http://live.mp3quran.net:9828",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "محمد جبريل",
    nameEn: "Mohammed Jibril",
    url: "http://live.mp3quran.net:9962",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "محمد رشاد الشريف",
    nameEn: "Mohammad Rashad Al-Shareef",
    url: "http://live.mp3quran.net:9830",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "محمد صديق المنشاوي — مرتل",
    nameEn: "Al-Minshawi (Murattal)",
    url: "http://live.mp3quran.net:9978",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "محمد صديق المنشاوي — مجوّد",
    nameEn: "Al-Minshawi (Mujawwad)",
    url: "http://live.mp3quran.net:9826",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "محمد عبدالكريم — رواية ١",
    nameEn: "Mohammad Abdul-Karim (Riwayah 1)",
    url: "http://live.mp3quran.net:9824",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "محمد عبدالكريم — رواية ٢",
    nameEn: "Mohammad Abdul-Karim (Riwayah 2)",
    url: "http://live.mp3quran.net:9822",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "محمد عبدالحكيم سعيد العبدالله — رواية ١",
    nameEn: "Mohammad Al-Abdullah (Riwayah 1)",
    url: "http://live.mp3quran.net:9814",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "محمد عبدالحكيم سعيد العبدالله — رواية ٢",
    nameEn: "Mohammad Al-Abdullah (Riwayah 2)",
    url: "http://live.mp3quran.net:9816",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "محمد عثمان خان",
    nameEn: "Mohammed Osman Khan",
    url: "http://live.mp3quran.net:9820",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "محمود خليل الحصري — مرتل",
    nameEn: "Al-Husary (Murattal)",
    url: "http://live.mp3quran.net:9958",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "محمود خليل الحصري — مجوّد",
    nameEn: "Al-Husary (Mujawwad)",
    url: "http://live.mp3quran.net:9806",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "محمود خليل الحصري — معلّم",
    nameEn: "Al-Husary (Muallim)",
    url: "http://live.mp3quran.net:9804",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "محمود علي البنا — رواية ١",
    nameEn: "Mahmoud Ali Al-Banna (Riwayah 1)",
    url: "http://live.mp3quran.net:9808",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "محمود علي البنا — رواية ٢",
    nameEn: "Mahmoud Ali Al-Banna (Riwayah 2)",
    url: "http://live.mp3quran.net:9810",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "محمود الرفاعي",
    nameEn: "Mahmoud Al-Rifai",
    url: "http://live.mp3quran.net:9818",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "محمود الشيمي",
    nameEn: "Mahmoud Al-Sheemy",
    url: "http://live.mp3quran.net:9812",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "مشاري راشد العفاسي",
    nameEn: "Mishary Rashid Al-Afasy",
    url: "http://live.mp3quran.net:8010",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "مصطفى إسماعيل",
    nameEn: "Mustafa Ismail",
    url: "http://live.mp3quran.net:9800",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "مصطفى اللاهوني",
    nameEn: "Mustafa Al-Lahuni",
    url: "http://live.mp3quran.net:9798",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "مصطفى رعد العزاوي",
    nameEn: "Mustafa Raad Al-Azawi",
    url: "http://live.mp3quran.net:9796",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "مفتاح السلطني — رواية ١",
    nameEn: "Muftah Al-Sultani (Riwayah 1)",
    url: "http://live.mp3quran.net:9790",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "مفتاح السلطني — رواية ٢",
    nameEn: "Muftah Al-Sultani (Riwayah 2)",
    url: "http://live.mp3quran.net:9792",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "مفتاح السلطني — رواية ٣",
    nameEn: "Muftah Al-Sultani (Riwayah 3)",
    url: "http://live.mp3quran.net:9788",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "مفتاح السلطني — رواية ٤",
    nameEn: "Muftah Al-Sultani (Riwayah 4)",
    url: "http://live.mp3quran.net:9794",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "معيض الحارثي",
    nameEn: "Mueedh Al-Harthi",
    url: "http://live.mp3quran.net:9802",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "موسى بلال",
    nameEn: "Mousa Bilal",
    url: "http://live.mp3quran.net:9786",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "ناصر القطامي",
    nameEn: "Nasser Al-Qatami",
    url: "http://live.mp3quran.net:9994",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "نبيل الرفاعي",
    nameEn: "Nabil Al-Rifai",
    url: "http://live.mp3quran.net:9784",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "نعمة الحسان",
    nameEn: "Niama Al-Hassan",
    url: "http://live.mp3quran.net:9782",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "هاني الرفاعي",
    nameEn: "Hani Al-Rifai",
    url: "http://live.mp3quran.net:9780",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "وليد النائحي",
    nameEn: "Walid Al-Naihi",
    url: "http://live.mp3quran.net:9778",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "ياسر الدوسري",
    nameEn: "Yasser Al-Dosari",
    url: "http://live.mp3quran.net:9984",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "ياسر القرشي",
    nameEn: "Yasser Al-Qurashi",
    url: "http://live.mp3quran.net:9776",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "ياسر المزروعي",
    nameEn: "Yasser Al-Mazrouei",
    url: "http://live.mp3quran.net:9774",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "يحيى حوا",
    nameEn: "Yahya Hawwa",
    url: "http://live.mp3quran.net:9772",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "يوسف الشويعي",
    nameEn: "Yousef Al-Shuaey",
    url: "http://live.mp3quran.net:9770",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "يوسف بن نوح أحمد",
    nameEn: "Yousef bin Noah Ahmad",
    url: "http://live.mp3quran.net:9768",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "أحمد خضر الطرابلسي",
    nameEn: "Ahmad Khader Al-Tarabulsi",
    url: "http://live.mp3quran.net:9924",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "أحمد الطرابلسي",
    nameEn: "Ahmad Al-Tarabulsi",
    url: "http://live.mp3quran.net:9926",
    category: "reciters",
    icon: faMicrophone,
  },
  {
    nameAr: "أحمد عامر",
    nameEn: "Ahmed Amer",
    url: "http://live.mp3quran.net:9920",
    category: "reciters",
    icon: faMicrophone,
  },

  // ── Translations ──────────────────────────
  {
    nameAr: "ترجمة إنجليزية (بصفر)",
    nameEn: "English Translation (Basfar)",
    url: "http://live.mp3quran.net:9754",
    category: "translations",
    icon: faGlobe,
  },
  {
    nameAr: "ترجمة إنجليزية (بيكثال)",
    nameEn: "English Translation (Pickthall)",
    url: "http://live.mp3quran.net:9748",
    category: "translations",
    icon: faGlobe,
  },
  {
    nameAr: "ترجمة إنجليزية (صحيح إنترناشيونال)",
    nameEn: "English Translation (Saheeh Int'l)",
    url: "http://live.mp3quran.net:9746",
    category: "translations",
    icon: faGlobe,
  },
  {
    nameAr: "ترجمة إسبانية",
    nameEn: "Spanish Translation",
    url: "http://live.mp3quran.net:9756",
    category: "translations",
    icon: faGlobe,
  },
  {
    nameAr: "ترجمة فرنسية",
    nameEn: "French Translation",
    url: "http://live.mp3quran.net:9744",
    category: "translations",
    icon: faGlobe,
  },
  {
    nameAr: "ترجمة ألمانية",
    nameEn: "German Translation",
    url: "http://live.mp3quran.net:9742",
    category: "translations",
    icon: faGlobe,
  },
  {
    nameAr: "ترجمة أوردية (عبدالباسط)",
    nameEn: "Urdu Translation (Abdul-Basit)",
    url: "http://live.mp3quran.net:9752",
    category: "translations",
    icon: faGlobe,
  },
  {
    nameAr: "ترجمة أوردية (المنشاوي)",
    nameEn: "Urdu Translation (Al-Minshawi)",
    url: "http://live.mp3quran.net:9758",
    category: "translations",
    icon: faGlobe,
  },
  {
    nameAr: "ترجمة أوردية (السديس والشريم)",
    nameEn: "Urdu Translation (Al-Sudais & Al-Shuraim)",
    url: "http://live.mp3quran.net:9750",
    category: "translations",
    icon: faGlobe,
  },
  {
    nameAr: "ترجمة تركية",
    nameEn: "Turkish Translation",
    url: "http://live.mp3quran.net:9764",
    category: "translations",
    icon: faGlobe,
  },
  {
    nameAr: "ترجمة صينية",
    nameEn: "Chinese Translation",
    url: "http://live.mp3quran.net:9766",
    category: "translations",
    icon: faGlobe,
  },
  {
    nameAr: "ترجمة كردية",
    nameEn: "Kurdish Translation",
    url: "http://live.mp3quran.net:9762",
    category: "translations",
    icon: faGlobe,
  },
  {
    nameAr: "ترجمة أمازيغية",
    nameEn: "Tamazight Translation",
    url: "http://live.mp3quran.net:9760",
    category: "translations",
    icon: faGlobe,
  },
];

export const categoryLabels: Record<RadioCategory, { ar: string; en: string }> =
  {
    main: { ar: "المحطات الرئيسية", en: "Main Stations" },
    thematic: { ar: "القنوات المتخصصة", en: "Specialised Channels" },
    reciters: { ar: "القرّاء", en: "Reciters" },
    translations: { ar: "الترجمات", en: "Translations" },
  };
